# Linear Algebraic Equations and Matrices (Ch. 8)



## Solving a Linear System of Equations

$$ Ax = b $$

* Use Python built-in function ```np.linalg.solve```

In [1]:
import numpy as np 


In [9]:
# Example 8.2

A = np.matrix(' 150 -100 0; \
               -100 150 -50; \
                 0  -50  50')
b = np.matrix(' 588.6; 686.7; 784.8 ')

x = np.linalg.solve(A,b)
print('solution x=\n',x)


solution x=
 [[41.202]
 [55.917]
 [71.613]]


In [13]:
# sanity check
residual = x - np.linalg.inv(A)*b
print('residual = ',residual)

residual =  [[-7.10542736e-15]
 [ 0.00000000e+00]
 [ 0.00000000e+00]]


In [14]:
# Use Numpy array 
A = np.array([[150,-100,0],\
              [-100, 150, -50],\
              [0, -50, 50]])
b = np.array([588.6, 686.7, 784.8 ])

x = np.linalg.solve(A,b)
print('solution x=\n',x)


solution x=
 [41.202 55.917 71.613]


## Case Study 8.3: Currents and Vortages in Circuits


**Kirchoff's current law** 

Sum of all the currents entering a node must be zero, 
$$ \sum i = 0 $$
where $i$ is current. 

**Ohm's law**

The electric current through a conductor between two points is directly proportional to the voltage across the two points.
$$ V = IR $$ 
where $V$ is the voltage; $I$ is the current; and $R$ is the registance. 

In [22]:
# Figure 8.8

# V1, V6 are given
# R12, R23, R34, R45, R56, R25 are given.
# Find the vortages at node2, node3, node4, node5

V1 = 200.0
V6 = 0.0

R12 = 5.0
R23 = 10.0
R34 = 5.0
R45 = 15.0
R56 = 20.0
R25 = 10.0

# Entries of A 
a11 = 1.0/R12 + 1.0/R23 + 1.0/R25 
a12 = - 1.0/R23 
a13 = 0.0
a14 = -1.0/R25

a21 = -1.0/R23 
a22 = 1.0/R23 + 1.0/R34 
a23 = -1.0/R34 
a24 = 0.0

a31 = 0.0
a32 = -1.0/R34 
a33 = 1.0/R34 + 1.0/R45 
a34 = -1.0/R45 

a41 = -1.0/R25 
a42 = 0.0
a43 = -1.0/R45 
a44 = 1.0/R25 + 1.0/R45 + 1.0/R56

# b
b1 = V1/R12 
b2 = 0.0
b3 = 0.0
b4 = V6/R56 

# construct A and b 
A = np.array([  [a11,a12,a13,a14],\
                [a21,a22,a23,a24],\
                [a31,a32,a33,a34],\
                [a41,a42,a43,a44]])
b = np.array([b1,b2,b3,b4])

x = np.linalg.solve(A,b)
print('solution x=\n',x)

# voltages 
V2 = x[0]
V3 = x[1]
V4 = x[2]
V5 = x[3]

# currents
i12 = (V1 - V2)/R12 
i23 = (V2 - V3)/R23
i25 = (V2 - V5)/R25 
i34 = (V3 - V4)/R34 
i45 = (V4 - V5)/R45 
i56 = (V5 - V6)/R56 

print('i12 = ',i12)
print('i23 = ',i23)
print('i25 = ',i25)
print('i34 = ',i34)
print('i45 = ',i45)
print('i56 = ',i56)

solution x=
 [169.23076923 153.84615385 146.15384615 123.07692308]
i12 =  6.153846153846155
i23 =  1.5384615384615359
i25 =  4.615384615384616
i34 =  1.5384615384615414
i45 =  1.5384615384615397
i56 =  6.153846153846153
