# LU Factorization (Ch. 10)



Use LU factorization function from Scipy library
```sc.linalg.lu```


In [16]:
import scipy as sc 
import numpy as np 


A = np.array([[3, -0.1, -0.2], [0.1, 7, -0.3], [0.3, -0.2, 10]])
b = np.array([0.3, -0.2, 10])

P,L,U = sc.linalg.lu(A)
print('Permutation Matrix =\n',P)
print('Lower Triangular Matrix =\n',L)
print('Upper Triangular Matrix =\n',U)
             
# sanity check             
print(np.matmul(L,U)-A)

# solution 
x_sol = np.linalg.solve(A,b)
_d = np.linalg.solve(L,b)
x = np.linalg.solve(U,_d)
print('x_sol= ', x_sol)
print('x_lu = ', x)
print('x_sol - x_lu = ', x_sol - x)


Permutation Matrix =
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Lower Triangular Matrix =
 [[ 1.          0.          0.        ]
 [ 0.03333333  1.          0.        ]
 [ 0.1        -0.02712994  1.        ]]
Upper Triangular Matrix =
 [[ 3.         -0.1        -0.2       ]
 [ 0.          7.00333333 -0.29333333]
 [ 0.          0.         10.01204188]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
x_sol=  [0.16673877 0.01169938 0.99523182]
x_lu =  [0.16673877 0.01169938 0.99523182]
x_sol - x_lu =  [0. 0. 0.]


Use Cholesky factorization function from Scipy library
```sc.linalg.cholesky```


In [29]:
import scipy as sc 
import numpy as np 


# consider a symmtric matrix A
A = np.array([[4, 12, -16], [12, 37, -43], [-16, -43, 98]])
x = np.ones([3])
b = np.dot(A,x)
print('A = \n', A)
print('x = \n', x)
print('b = \n', b)

# compute U such that A = U^T U
U = sc.linalg.cholesky(A,lower=False)  
print('U = \n', U)

# sanity check
print(np.matmul(U.transpose(),U)-A)

# 1. Solve for d
_d = np.linalg.solve(U.transpose(),b)

# 2. Solve for x 
x = np.linalg.solve(U,_d)
print('x=  \n',x)



A = 
 [[  4  12 -16]
 [ 12  37 -43]
 [-16 -43  98]]
x = 
 [1. 1. 1.]
b = 
 [ 0.  6. 39.]
U = 
 [[ 2.  6. -8.]
 [ 0.  1.  5.]
 [ 0.  0.  3.]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
x=  
 [1. 1. 1.]


In [30]:
# compute L such that A = L L^T
L = sc.linalg.cholesky(A,lower=True)  
print('L = \n', L)

# sanity check
print(np.matmul(L,L.transpose())-A)

# 1. Solve for d
_d = np.linalg.solve(L,b)

# 2. Solve for x 
x = np.linalg.solve(L.transpose(),_d)
print('x=  \n',x)

L = 
 [[ 2.  0.  0.]
 [ 6.  1.  0.]
 [-8.  5.  3.]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
x=  
 [1. 1. 1.]
