# Iterative Methods (Ch. 12)



Use Numpy function for computing the inverse matrix
```np.linalg.inv```


In [11]:
import numpy as np

A = np.array([[3, -0.1, -0.2],  
              [0.1, 7, -0.3], 
              [0.3, -0.2, 10]])

b = np.array([7.85, -19.3, 71.4])
x_sol = np.linalg.solve(A,b)

print('A = \n', A)
print('b = \n', b)
print('solution = \n', x_sol)


A = 
 [[ 3.  -0.1 -0.2]
 [ 0.1  7.  -0.3]
 [ 0.3 -0.2 10. ]]
b = 
 [  7.85 -19.3   71.4 ]
solution = 
 [ 3.  -2.5  7. ]


In [15]:
# Decompose A into L + D + U matrices
m,n = A.shape
print('m={}, n={}'.format(m,n))
L = np.zeros([m,n])
D = np.zeros([m,n])
U = np.zeros([m,n])
for i in range(m):
    L[i,0:i] = A[i,0:i]
    D[i,i] = A[i,i]
    U[i,i+1:] = A[i,i+1:]

print('L = \n', L)
print('D = \n', D)
print('U = \n', U)




m=3, n=3
L = 
 [[ 0.   0.   0. ]
 [ 0.1  0.   0. ]
 [ 0.3 -0.2  0. ]]
D = 
 [[ 3.  0.  0.]
 [ 0.  7.  0.]
 [ 0.  0. 10.]]
U = 
 [[ 0.  -0.1 -0.2]
 [ 0.   0.  -0.3]
 [ 0.   0.   0. ]]


The condition number measures 
 how much the output value can change for a small change in the input argument.

In [19]:
# Gauss-Seidel

# - - - - 1st iteration - - - - 
# initial condition
x0 = np.zeros([n])

lhs = L + D
rhs = b - U.dot(x0)
x1 = np.linalg.solve(lhs,rhs)
print('1st iteration = ', x1)

# - - - - 2nd iteration - - - - 

lhs = L + D
rhs = b - U.dot(x1)
x2 = np.linalg.solve(lhs,rhs)
print('2nd iteration = ', x2)


1st iteration =  [ 2.61666667 -2.79452381  7.00560952]
2nd iteration =  [ 2.99055651 -2.49962468  7.00029081]


In [22]:
# error computation
ea2 = abs((x2 - x1)/x2) * 100 
print('{0:10d}  {1:16.13f} {2:16.13f} {3:16.13f}'.format(2,ea2[0],ea2[1],ea2[2]))


         2  12.5023499899631 11.7977361365069  0.0759784541430
