# Gauss Elimination (Ch. 9)



## Crammer's Rule


In [28]:
import numpy as np 

# A = np.matrix(' 0.3, 0.52,  1.0;  \
#                 0.5, 1.0,  1.9;  \
#                 0.1,  0.3,   0.5; ')

A = np.matrix(' 0.3 0.52  1.0;  \
                0.5 1.00  1.9;  \
                0.1  0.3  0.5 ')

b = np.matrix('-0.01;  0.67;  -0.44')

x = np.linalg.solve(A,b)
print('solution x=\n',x)


solution x=
 [[-14.9]
 [-29.5]
 [ 19.8]]


In [31]:
A1 = np.array(A)
b1 = np.array(b)
A1[:,0] = b1[:,0]

In [33]:
# determinant 
D = np.linalg.det(A)

# convert matrix A and b to numpy arrays
A = np.array(A)
b = np.array(b)

# substitute the first column of A with b
A1 = np.copy(A)
A1[:,0] = b[:,0]
print('A = \n',A)
print('A1= \n',A1)

x1 = np.linalg.det(A1)/D
print(x1)

# substitute the second column of A with b
A2 = np.copy(A)
A2[:,1] = b[:,0]
print('A = \n',A)
print('A2= \n',A2)

x2 = np.linalg.det(A2)/D
print(x2)

# substitute the second column of A with b
A3 = np.copy(A)
A3[:,2] = b[:,0]
print('A = \n',A)
print('A3= \n',A3)

x3 = np.linalg.det(A3)/D
print(x3)

A = 
 [[0.3  0.52 1.  ]
 [0.5  1.   1.9 ]
 [0.1  0.3  0.5 ]]
A1= 
 [[-0.01  0.52  1.  ]
 [ 0.67  1.    1.9 ]
 [-0.44  0.3   0.5 ]]
-14.899999999999983
A = 
 [[0.3  0.52 1.  ]
 [0.5  1.   1.9 ]
 [0.1  0.3  0.5 ]]
A2= 
 [[ 0.3  -0.01  1.  ]
 [ 0.5   0.67  1.9 ]
 [ 0.1  -0.44  0.5 ]]
-29.500000000000032
A = 
 [[0.3  0.52 1.  ]
 [0.5  1.   1.9 ]
 [0.1  0.3  0.5 ]]
A3= 
 [[ 0.3   0.52 -0.01]
 [ 0.5   1.    0.67]
 [ 0.1   0.3  -0.44]]
19.800000000000022


## Naive Gaussian Elimination

In [34]:
# Figure 9.4 

def gaussnaive(A,b):
    (m,n) = A.shape
    if m!=n:
        return Exception('Matrix A should be square!')
    nb = n + 1 # size of augmented matrix
    # build augmented matrix
    Aug = np.hstack((A,b))
    print('Augmented matrix = ',Aug)
    # 1. forward elimination
    # we use (n-1) pivot equations, 
    for k in range(n-1): # k=0,1,...,n-2
        # Aug[k,k] is the pivot element
        # Aug[k,k:nb] is the pivot equation, (n-k+1) elements 
        for i in range(k+1,n): # (n-k-1) iteration 
            print(i)
            factor = Aug[i,k] / Aug[k,k] # 1 division
            Aug[i,k:nb] = Aug[i,k:nb] - factor * Aug[k,k:nb] # (n-k+1) multiplication and subtraction

    # 2. back substitution
    x = np.zeros([n,1])
    x = np.matrix(x)
    x[n-1] = Aug[n-1,nb-1]/ Aug[n-1,n-1]
    for i in range(n-2,-1,-1): # n-2,n-3,...,2,1,0 => (n-1) iteration
        x[i] = (Aug[i,nb-1]-Aug[i,i+1:n]*x[i+1:n,0])/Aug[i,i] # (n-i) multiplication, 1 division, 1 subtraction, (n-i-1)addition
    return Aug, x

In [35]:

Aug, x = gaussnaive(A,b)
print(Aug )

Augmented matrix =  [[ 0.3   0.52  1.   -0.01]
 [ 0.5   1.    1.9   0.67]
 [ 0.1   0.3   0.5  -0.44]]
1
2
2
[[ 0.3         0.52        1.         -0.01      ]
 [ 0.          0.13333333  0.23333333  0.68666667]
 [ 0.          0.         -0.055      -1.089     ]]


## Gaussian Elimination with Pivot

In [36]:
# Figure 9.6 

def maxrow(avec):
    maxrowIdx = 0
    n = len(avec)
    amax = abs(avec[0])
    for i in range(1,n):
        if (abs(avec[i])) > amax:
            amax = avec[i]
            maxrowIdx = i 
    return maxrowIdx

def gausspivot(A,b):
    (m,n) = A.shape
    if m!=n:
        return Exception('Matrix A should be square!')
    nb = n + 1 # size of augmented matrix
    # build augmented matrix
    Aug = np.hstack((A,b))
    print('Augmented matrix = ',Aug)
    # 1. forward elimination
    for k in range(n-1): 
        # Aug[k,k] is the pivot element
        # Aug[k,k:nb] is the pivot equation
        # partial pivoting
        imax = maxrow(Aug[k:n,k])
        ipr = imax + k
        if ipr !=k: # no swap if pivot is max
            for j in range(k,nb): # swap rows k and ipr 
                temp= Aug[k,j]
                Aug[k,j] = Aug[ipr,j]
                Aug[ipr,j] = temp
        
        for i in range(k+1,n):  
            print(i)
            factor = Aug[i,k] / Aug[k,k]  
            Aug[i,k:nb] = Aug[i,k:nb] - factor * Aug[k,k:nb] 

    # 2. back substitution
    x = np.zeros([n,1])
    x = np.matrix(x)
    x[n-1] = Aug[n-1,nb-1]/ Aug[n-1,n-1]
    for i in range(n-2,-1,-1):
        x[i] = (Aug[i,nb-1]-Aug[i,i+1:n]*x[i+1:n,0])/Aug[i,i]
    return Aug, x

In [37]:
A = np.matrix(' 0.0 -3.0  7.0;  \
                1.0  2.0  -1.0;  \
                5.0  -2.0  0.0 ')

b = np.matrix('4;  0;  3')

x = np.linalg.solve(A,b)
print('solution x=\n',x)

solution x=
 [[ 0.5942029 ]
 [-0.01449275]
 [ 0.56521739]]


In [39]:
Aug, x = gaussnaive(A,b)
print(Aug )

Augmented matrix =  [[ 0. -3.  7.  4.]
 [ 1.  2. -1.  0.]
 [ 5. -2.  0.  3.]]
1
2
2
[[  0.  -3.   7.   4.]
 [ nan  inf -inf -inf]
 [ nan  nan  nan  nan]]


/var/folders/hh/w5xjnck119d_h0x6gxztgrwr0000gn/T/ipykernel_53731/2691583130.py:18: RuntimeWarning: divide by zero encountered in scalar divide
  factor = Aug[i,k] / Aug[k,k] # 1 division
/var/folders/hh/w5xjnck119d_h0x6gxztgrwr0000gn/T/ipykernel_53731/2691583130.py:19: RuntimeWarning: invalid value encountered in multiply
  Aug[i,k:nb] = Aug[i,k:nb] - factor * Aug[k,k:nb] # (n-k+1) multiplication and subtraction
/var/folders/hh/w5xjnck119d_h0x6gxztgrwr0000gn/T/ipykernel_53731/2691583130.py:18: RuntimeWarning: invalid value encountered in scalar divide
  factor = Aug[i,k] / Aug[k,k] # 1 division


In [38]:
Aug,x = gausspivot(A,b)

print(Aug)
print(x)

Augmented matrix =  [[ 0. -3.  7.  4.]
 [ 1.  2. -1.  0.]
 [ 5. -2.  0.  3.]]
1
2
2
[[ 5.  -2.   0.   3. ]
 [ 0.  -3.   7.   4. ]
 [ 0.   0.   4.6  2.6]]
[[ 0.5942029 ]
 [-0.01449275]
 [ 0.56521739]]


## Thomas Algorithm

In [52]:
# Figure 9.7

def tridiag(e,f,g,r):
    n = len(f)
    #forward elimination
    x = np.zeros([n])
    for k in range(1,n):
        factor = e[k]/f[k-1]
        f[k] = f[k] - factor*g[k-1]
        r[k] = r[k] - factor*r[k-1]
    # back substitution
    x[n-1] = r[n-1]/f[n-1]
    for k in range(n-2,-1,-1):
        x[k] = ( r[k] - g[k] * x[k+1] ) / f[k]

    return x

In [43]:
A = np.matrix(' 2.04  -1.0   0.0  0.0;  \
                -1.0  2.04  -1.0  0.0;  \
                0.0   -1.0  2.04  -1.0; \
                0.0    0.0  -1.0  2.04')

b = np.matrix('40.8;  0.8;  0.8;   200.8')

x = np.linalg.solve(A,b)
print('solution x=\n',x)

solution x=
 [[ 65.96983437]
 [ 93.77846211]
 [124.53822833]
 [159.47952369]]


In [55]:
e = -np.ones([4]) # 3 elements
g = -np.ones([4]) # 3 elements
f = np.ones([4])*2.04 # 4 elements
r = np.squeeze(np.array(b)) # 4 elements

x = tridiag(e,f,g,r)
print(x)


[ 65.96983437  93.77846211 124.53822833 159.47952369]
