# Matrix Inverse and Condition (Ch. 11)



Use Numpy function for computing the inverse matrix
```np.linalg.inv```


In [3]:
import numpy as np

A = np.array([[1, 2], [3, 4]])
print('Inverse of A = \n',np.linalg.inv(A))

Inverse of A = 
 [[-2.   1. ]
 [ 1.5 -0.5]]


In [2]:
# Why do you think this is not working? 
A = np.array([[1, 2], [2, 4]])
np.linalg.inv(A)

LinAlgError: Singular matrix

The condition number measures 
 how much the output value can change for a small change in the input argument.

In [5]:
import numpy as np 

A = np.array([[1, 1/2, 1/3], [1/2, 1/3, 1/4],[1/3,1/4,1/5]])
print(' A = \n',A)
print('Inverse of A = \n',np.linalg.inv(A))

# scaling
A_scale = np.array([[1, 1/2, 1/3], [1, 2/3, 1/2],[1,3/4,3/5]])
A_scale_inv = np.linalg.inv(A_scale)
print('Inverse of A_scale = \n',A_scale_inv)

# condition number for A_scale w.r.t. row-sum norm
print('condition number of A_scale = \n',np.linalg.cond(A_scale,np.inf))

# condition number for A_scale w.r.t. column-sum norm
print('condition number of A_scale = \n',np.linalg.cond(A_scale,1))

# condition number for A_scale w.r.t. two norm
print('condition number of A_scale = \n',np.linalg.cond(A_scale,2))

# condition number for A_scale w.r.t. Frobenius norm
print('condition number of A_scale = \n',np.linalg.cond(A_scale))
print('condition number of A_scale = \n',np.linalg.norm(A_scale,2)*np.linalg.norm(A_scale_inv,2))

# 




 A = 
 [[1.         0.5        0.33333333]
 [0.5        0.33333333 0.25      ]
 [0.33333333 0.25       0.2       ]]
Inverse of A = 
 [[   9.  -36.   30.]
 [ -36.  192. -180.]
 [  30. -180.  180.]]
Inverse of A_scale = 
 [[  9. -18.  10.]
 [-36.  96. -60.]
 [ 30. -90.  60.]]
condition number of A_scale = 
 451.2000000000027
condition number of A_scale = 
 612.0000000000036
condition number of A_scale = 
 366.350323236704
condition number of A_scale = 
 366.350323236704
condition number of A_scale = 
 366.3503232367038
